const observer = new IntersectionObserver((entries) => entries.forEach(({ isIntersecting, target }) => { if (isIntersecting) { target.classList.add('visible'); observer.unobserve(target); } }), { threshold: 0.12 });
document.querySelectorAll('.reveal').forEach((element) => observer.observe(element));
document.title = 'Alexsander Ornelas | Analista de Dados';
const favicon = document.createElement('link');
favicon.rel = 'icon'; favicon.type = 'image/svg+xml'; favicon.href = 'favicon.svg'; document.head.append(favicon);
const certificationsStyles = document.createElement('link');
certificationsStyles.rel = 'stylesheet'; certificationsStyles.href = 'certifications.css'; document.head.append(certificationsStyles);
const careerScript = document.createElement('script');
careerScript.src = 'content-updates.js';
careerScript.onload = () => { const oldToggle=document.querySelector('#language-toggle'); const cleanToggle=oldToggle.cloneNode(true); oldToggle.replaceWith(cleanToggle); cleanToggle.addEventListener('click',()=>{currentLanguage=currentLanguage==='pt'?'en':'pt';applyFullLanguage(currentLanguage);updateWhatsApp(currentLanguage);window.renderCareer(currentLanguage);const labels=currentLanguage==='en'?['HOME','ABOUT','STACK','EXPERIENCE','CERTIFICATIONS','PORTFOLIO','CONTACT']:['INÍCIO','SOBRE','STACK','EXPERIÊNCIA','CERTIFICAÇÕES','PORTFÓLIO','CONTATO'];document.querySelectorAll('.topbar nav a').forEach((link,i)=>link.textContent=labels[i]);const aboutWA=document.querySelector('.about-whatsapp');if(aboutWA)aboutWA.href=`https://wa.me/5561995694388?text=${encodeURIComponent(currentLanguage==='en'?'Hello, Alexsander. I visited your portfolio and would like to discuss a data-related opportunity or project.':'Olá, Alexsander. Visitei seu portfólio e gostaria de conversar sobre uma oportunidade ou projeto na área de dados.')}`;}); };
document.body.append(careerScript);
const allCertificationsScript = document.createElement('script');
allCertificationsScript.src = 'all-certifications.js'; document.body.append(allCertificationsScript);
const updateStyles = document.createElement('link');
updateStyles.rel = 'stylesheet'; updateStyles.href = 'updates.css'; document.head.append(updateStyles);
const languageToggle = document.querySelector('#language-toggle');
const translations = { en: { nav: ['HOME', 'ABOUT', 'STACK', 'EXPERIENCE', 'PORTFOLIO', 'CONTACT'], kicker: 'DATA ANALYST · BUSINESS INTELLIGENCE', typing: 'I turn data into decisions', contact: 'LET’S TALK?', button: 'Talk to me' }, pt: { nav: ['INÍCIO', 'SOBRE', 'STACK', 'EXPERIÊNCIA', 'PORTFÓLIO', 'CONTATO'], kicker: 'ANALISTA DE DADOS · BUSINESS INTELLIGENCE', typing: 'Eu transformo dados em decisões', contact: 'VAMOS CONVERSAR?', button: 'Fale comigo' } };
let currentLanguage = 'pt';
languageToggle?.addEventListener('click', () => { currentLanguage = currentLanguage === 'pt' ? 'en' : 'pt'; const t = translations[currentLanguage]; document.querySelectorAll('.topbar nav a').forEach((link, index) => { link.textContent = t.nav[index]; }); document.querySelector('.hero-kicker').textContent = t.kicker; document.querySelector('.typing').childNodes[0].textContent = t.typing; document.querySelector('.contact > div > p').textContent = t.contact; document.querySelector('.solid').childNodes[0].textContent = `${t.button} `; languageToggle.textContent = currentLanguage === 'pt' ? 'EN' : 'PT'; languageToggle.setAttribute('aria-label', currentLanguage === 'pt' ? 'Mudar idioma para inglês' : 'Change language to Portuguese'); document.documentElement.lang = currentLanguage === 'pt' ? 'pt-BR' : 'en'; });
const finalStyles = document.createElement('link');
finalStyles.rel = 'stylesheet'; finalStyles.href = 'final-tweaks.css'; document.head.append(finalStyles);
const correctionStyles = document.createElement('link');
correctionStyles.rel = 'stylesheet'; correctionStyles.href = 'corrections.css'; document.head.append(correctionStyles);
const heroPhoto = document.createElement('img');
heroPhoto.src = 'alexsander-photo.png'; heroPhoto.alt = 'Alexsander Ornelas'; heroPhoto.className = 'hero-portrait'; document.querySelector('.hero').append(heroPhoto);
const i18n = {
  pt: { nav:['INÍCIO','SOBRE','STACK','EXPERIÊNCIA','PORTFÓLIO','CONTATO'], heroKicker:'ANALISTA DE DADOS · BUSINESS INTELLIGENCE', typing:'Eu transformo dados em decisões', description:'Dashboards, automações e produtos de dados que tornam o negócio mais claro, rápido e estratégico.', solid:'Fale comigo ', outline:'Ver experiências ', scroll:'ROLE PARA EXPLORAR ', about:'Sobre', intro:'Olá, eu sou o Alexsander.', aboutTitle:'Dados são mais valiosos quando viram <em>direção.</em>', aboutText:'Sou um profissional de dados apaixonado por transformar perguntas complexas em respostas simples e acionáveis. Com mais de três anos de experiência, já atuei em BI, engenharia de dados e automação, criando dashboards estratégicos e pipelines para os times financeiro, comercial, educacional, RH e marketing.', stack:'Stack', stackLead:'Tecnologias e ferramentas que domino para construir soluções de ponta a ponta.', exp:'Experiências', expLead:'Uma trajetória técnica, orientada a resolver problemas reais de negócio.', portfolio:'Portfólio', portfolioLead:'Seleção de dashboards e produtos analíticos desenvolvidos em Power BI.', contact:'VAMOS CONVERSAR?', contactTitle:'Seu próximo desafio<br>merece dados <em>melhores.</em>', dashTitle:'Análise Executiva', dashSub:'RESULTADOS · YTD', project:'Dashboard Executivo', projectText:'Indicadores para leitura rápida de performance e resultados.', footer:'© 2026 Alexsander Ornelas', role:'Analista de Dados' },
  en: { nav:['HOME','ABOUT','STACK','EXPERIENCE','PORTFOLIO','CONTACT'], heroKicker:'DATA ANALYST · BUSINESS INTELLIGENCE', typing:'I turn data into decisions', description:'Dashboards, automations and data products that make business clearer, faster and more strategic.', solid:'Talk to me ', outline:'View experience ', scroll:'SCROLL TO EXPLORE ', about:'About', intro:'Hi, I’m Alexsander.', aboutTitle:'Data becomes more valuable when it turns into <em>direction.</em>', aboutText:'I am a data professional passionate about turning complex questions into clear, actionable answers. With more than three years of experience, I have worked across BI, data engineering and automation, building strategic dashboards and pipelines for finance, sales, education, HR and marketing teams.', stack:'Stack', stackLead:'Technologies and tools I use to build end-to-end solutions.', exp:'Experience', expLead:'A technical journey focused on solving real business problems.', portfolio:'Portfolio', portfolioLead:'A selection of dashboards and analytical products built in Power BI.', contact:'LET’S TALK?', contactTitle:'Your next challenge<br>deserves <em>better data.</em>', dashTitle:'Executive Analytics', dashSub:'RESULTS · YTD', project:'Executive Dashboard', projectText:'Indicators for a quick read of performance and outcomes.', footer:'© 2026 Alexsander Ornelas', role:'Data Analyst' }
};
const applyLanguage = (lang) => { const t = i18n[lang]; document.querySelectorAll('.topbar nav a').forEach((el,i)=>el.textContent=t.nav[i]); document.querySelector('.hero-kicker').textContent=t.heroKicker; document.querySelector('.typing').childNodes[0].textContent=t.typing; document.querySelector('.hero-description').textContent=t.description; document.querySelector('.solid').childNodes[0].textContent=t.solid; document.querySelector('.outline').childNodes[0].textContent=t.outline; document.querySelector('.scroll').childNodes[0].textContent=t.scroll; const titles=document.querySelectorAll('.section-title h2'); [t.about,t.stack,t.exp,t.portfolio].forEach((v,i)=>titles[i].textContent=v); document.querySelector('.intro').textContent=t.intro; document.querySelector('.about h3').innerHTML=t.aboutTitle; document.querySelector('.about-copy>p:not(.intro)').textContent=t.aboutText; document.querySelector('.skills .section-lead').textContent=t.stackLead; document.querySelector('.experience .section-lead').textContent=t.expLead; document.querySelector('.portfolio .section-lead').textContent=t.portfolioLead; document.querySelector('.contact > div > p').textContent=t.contact; document.querySelector('.contact h2').innerHTML=t.contactTitle; document.querySelector('.chart-art b').textContent=t.dashTitle; document.querySelector('.chart-art span').textContent=t.dashSub; document.querySelector('.featured-project h3').textContent=t.project; document.querySelector('.featured-project p').textContent=t.projectText; document.querySelector('.profile figcaption span').textContent=t.role; document.querySelector('footer p').textContent=t.footer; const activeToggle=document.querySelector('#language-toggle'); activeToggle.textContent=lang==='pt'?'EN':'PT'; activeToggle.setAttribute('aria-label',lang==='pt'?'Mudar idioma para inglês':'Change language to Portuguese'); document.documentElement.lang=lang==='pt'?'pt-BR':'en'; };
languageToggle?.replaceWith(languageToggle.cloneNode(true));
const newToggle = document.querySelector('#language-toggle');
newToggle.addEventListener('click',()=>{currentLanguage=currentLanguage==='pt'?'en':'pt';applyLanguage(currentLanguage);});
applyLanguage('pt');
const fullTranslations = {
  pt: { stackCards:[['Business Intelligence','Dashboards com narrativa, clareza e foco em tomada de decisão.'],['Engenharia de Dados','Pipelines robustos, camadas de dados e automação de processos.'],['Banco & ETL','Dados confiáveis e prontos para análise, do dado bruto ao insight.'],['Produtos de Dados','Automação, aplicações internas e análises que destravam equipes.']], jobs:[['2024 — PRESENTE','Engenheiro de Dados','Desenvolvo soluções de dados para dar autonomia à liderança na leitura dos principais indicadores. Estruturei 8 dashboards estratégicos em Power BI, cobrindo DRE, educacional, fluxo de alunos, comercial, faturamento, inadimplência e NPS de cancelamento. Também automatizei a atualização de relatórios com pipelines no Microsoft Fabric, Data Factory, Lakehouse e notebooks PySpark. Com isso, informações que antes dependiam de levantamentos manuais passaram a estar disponíveis com mais consistência, velocidade e governança.'],['2023 — PRESENTE','Analista de Dados Pleno','Desenvolvo dashboards e produtos de dados para diferentes clientes e áreas de negócio, como financeiro, comercial, marketing, RH e DRE. Conduzo processos de ETL em SQL Server, com atenção à qualidade, rastreabilidade e governança das informações. Também crio automações com pipelines e PySpark para conjuntos de dados que variam de tabelas operacionais a volumes de múltiplos GB. Além disso, desenvolvo aplicações em Power Apps para otimizar processos internos e reduzir tarefas repetitivas.'],['2021 — 2024','Suporte Técnico N2 · Estagiário de TI','Iniciei minha trajetória profissional em tecnologia atuando com suporte técnico e infraestrutura. Fui responsável por monitorar redes, sistemas de comunicação digital e contas de usuários em ambientes Cloud e Active Directory. Atuei no suporte N2 para hardware, software e telefonia IP, acompanhando chamados e fornecedores. Essa experiência construiu uma base prática de diagnóstico, organização e visão operacional que hoje aplico à engenharia e análise de dados.']], projects:['Dashboard Executivo','Dashboard de Indicadores','Produto Analítico','Visão de Performance'], portfolio:'Portfólio', portfolioLead:'Seleção de dashboards e produtos analíticos desenvolvidos em Power BI.', dashboardTitle:'Visão Analítica Executiva', dashboardSub:'RECEITA · MARGEM · METAS', dashboardLabels:['Receita','Margem','Meta'], featureText:'Indicadores para leitura rápida de performance, resultado e evolução de metas.' },
  en: { stackCards:[['Business Intelligence','Dashboards with storytelling, clarity and a focus on decision-making.'],['Data Engineering','Robust pipelines, data layers and process automation.'],['Databases & ETL','Reliable data ready for analysis, from raw data to insight.'],['Data Products','Automation, internal apps and analysis that unlock teams.']], jobs:[['2024 — PRESENT','Data Engineer','I build data solutions that give leadership autonomy when reading key business indicators. I created 8 strategic Power BI dashboards covering P&L, education, student flow, sales, revenue, delinquency and cancellation NPS. I also automated report updates with pipelines in Microsoft Fabric, Data Factory, Lakehouse and PySpark notebooks. As a result, information that previously relied on manual preparation is now available with greater consistency, speed and governance.'],['2023 — PRESENT','Senior Data Analyst','I develop dashboards and data products for clients across finance, sales, marketing, HR and P&L. I lead ETL processes in SQL Server with close attention to data quality, traceability and governance. I also build automations with pipelines and PySpark for datasets ranging from operational tables to multiple-gigabyte volumes. In addition, I create Power Apps solutions that streamline internal processes and reduce repetitive work.'],['2021 — 2024','Technical Support N2 · IT Intern','I began my career in technology working with technical support and infrastructure. I monitored networks, digital communication systems and user accounts across Cloud and Active Directory environments. I provided N2 support for hardware, software and IP telephony while tracking tickets and vendor requests. This experience built the practical diagnostic, organization and operational perspective that I now apply to data engineering and analytics.']], projects:['Executive Dashboard','Indicators Dashboard','Analytical Product','Performance Overview'], portfolio:'Portfolio', portfolioLead:'A selection of dashboards and analytical products built in Power BI.', dashboardTitle:'Executive Analytics Overview', dashboardSub:'REVENUE · MARGIN · TARGETS', dashboardLabels:['Revenue','Margin','Target'], featureText:'Indicators for a quick read of performance, outcomes and target progress.' }
};
const applyFullLanguage = (lang) => { const t=fullTranslations[lang]; const base=i18n[lang]; applyLanguage(lang); document.querySelectorAll('.skill-grid article').forEach((card,i)=>{card.querySelector('h3').textContent=t.stackCards[i][0];card.querySelector('p').textContent=t.stackCards[i][1];}); document.querySelectorAll('.experience-list article').forEach((job,i)=>{job.querySelector('time').textContent=t.jobs[i][0];job.querySelector('h3').textContent=t.jobs[i][1];job.querySelector('p').textContent=t.jobs[i][2];}); document.querySelectorAll('.project-list h3').forEach((title,i)=>title.textContent=t.projects[i+1]); document.querySelector('.featured-project h3').textContent=t.projects[0]; document.querySelector('.portfolio .section-title h2').textContent=t.portfolio; document.querySelector('.portfolio .section-lead').textContent=t.portfolioLead; document.querySelector('.chart-art').innerHTML=`<div class="analytics-head"><b>${t.dashboardTitle}</b><span>${t.dashboardSub}</span></div><div class="analytics-kpis">${t.dashboardLabels.map((label,index)=>`<div><small>${label}</small><strong>${index===0?'R$ 2,4M':index===1?'34,8%':'112%'}</strong></div>`).join('')}</div><div class="analytics-bars"><i></i><i></i><i></i><i></i><i></i><i></i></div>`; document.querySelector('.featured-project p').textContent=t.featureText; };
const finalLanguageButton=document.querySelector('#language-toggle');
finalLanguageButton.replaceWith(finalLanguageButton.cloneNode(true));
const completeToggle=document.querySelector('#language-toggle');
completeToggle.addEventListener('click',()=>{currentLanguage=currentLanguage==='pt'?'en':'pt';applyFullLanguage(currentLanguage);});
fullTranslations.pt.jobs[3] = fullTranslations.pt.jobs[2];
fullTranslations.en.jobs[3] = fullTranslations.en.jobs[2];
applyFullLanguage('pt');
const motionStyles = document.createElement('link');
motionStyles.rel = 'stylesheet'; motionStyles.href = 'motion.css'; document.head.append(motionStyles);
const polishFixStyles = document.createElement('link');
polishFixStyles.rel = 'stylesheet'; polishFixStyles.href = 'polish-fix.css'; document.head.append(polishFixStyles);
const finalMotionStyles = document.createElement('link');
finalMotionStyles.rel = 'stylesheet'; finalMotionStyles.href = 'final-motion.css'; document.head.append(finalMotionStyles);
const profileImage = document.querySelector('.profile img');
if (profileImage) profileImage.src = 'alexsander-photo.png';
const navigation = [...document.querySelectorAll('.topbar nav a')];
const pageSections = [...document.querySelectorAll('main section[id]')];
pageSections.forEach(section => section.classList.add('section-motion'));
const sectionObserver = new IntersectionObserver((entries) => entries.forEach(entry => {
  if (!entry.isIntersecting) { entry.target.classList.remove('in-view'); return; }
  entry.target.classList.add('in-view');
  const activeId = entry.target.id;
  navigation.forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${activeId}`));
}), { rootMargin: '-28% 0px -42% 0px', threshold: 0.01 });
pageSections.forEach(section => sectionObserver.observe(section));
window.addEventListener('scroll', () => {
  const shift = Math.min(window.scrollY * .025, 20);
  document.documentElement.style.setProperty('--scroll-shift', `${shift}px`);
}, { passive: true });
const whatsappLink = document.querySelector('.whatsapp');
const whatsappMessages = { pt: 'Olá, Alexsander. Visitei seu portfólio e gostaria de conversar sobre uma oportunidade ou projeto na área de dados.', en: 'Hello, Alexsander. I visited your portfolio and would like to discuss a data-related opportunity or project.' };
const updateWhatsApp = (lang) => { if (whatsappLink) whatsappLink.href = `https://wa.me/5561995694388?text=${encodeURIComponent(whatsappMessages[lang])}`; };
updateWhatsApp('pt');
completeToggle.addEventListener('click', () => updateWhatsApp(currentLanguage));
window.addEventListener('scroll', () => { const contactSection=document.querySelector('#contato'); const contactReached=contactSection && contactSection.getBoundingClientRect().top < window.innerHeight*.55; const atBottom = window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 8; if (!contactReached && !atBottom) return; navigation.forEach(link => link.classList.toggle('active', link.getAttribute('href') === '#contato')); contactSection?.classList.add('in-view'); }, { passive: true });
const updateHeroSpecialties=()=>{const isEnglish=document.documentElement.lang==='en';document.querySelector('.hero-kicker').textContent=isEnglish?'DATA ANALYST · DATA ENGINEER · BUSINESS INTELLIGENCE':'ANALISTA DE DADOS · ENGENHEIRO DE DADOS · BUSINESS INTELLIGENCE';};updateHeroSpecialties();document.querySelector('#language-toggle').addEventListener('click',()=>setTimeout(updateHeroSpecialties,0));setInterval(updateHeroSpecialties,250);
const personalPortfolio={pt:{lead:'Dashboards pessoais desenvolvidos em Power BI, com foco em análises práticas e tomadas de decisão.',featured:'Análise de Vendas',description:'Dashboard pessoal desenvolvido para acompanhar indicadores, desempenho comercial e oportunidades de vendas.',projects:['Análise Financeira','KPIs de Recursos Humano','Fluo de Caixa com Simulador Financeiro','Setor Comercial','Atendimento Suporte de TI','Empresa de Roupas']},en:{lead:'Personal dashboards developed in Power BI, focused on practical analysis and decision-making.',featured:'Sales Analysis',description:'Personal dashboard developed to monitor key indicators, sales performance and commercial opportunities.',projects:['Financial Analysis','Human Resources KPIs','Cash Flow with Financial Simulator','Commercial Sector','IT Support Service','Clothing Company']}};
const personalPortfolioLinks=['https://app.powerbi.com/view?r=eyJrIjoiNzM5OGIyNGEtYjkzMi00Y2UxLTlhZmYtNzFlOTExNTgwZmM1IiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9','https://app.powerbi.com/view?r=eyJrIjoiMTFhYzk2MTItNDEwZi00ZWNlLWJjNDgtMzI0YzJiMjRhYjBiIiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9','https://app.powerbi.com/view?r=eyJrIjoiMmQzYzgxMzgtNTFlZC00YTI5LWE2NzUtMTA2OTZiYTY4NzAxIiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9','https://app.powerbi.com/view?r=eyJrIjoiNDc4Nzc5NTUtMWJlZS00Y2VhLWIxYTMtZmI4OWQxZGQ4NGVkIiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9','https://app.powerbi.com/view?r=eyJrIjoiYjQyYjU3Y2MtMzE5Ni00MThjLWJkNDEtYzMxNThiNTZhZWE4IiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9','https://app.powerbi.com/view?r=eyJrIjoiOWNkMDllMjEtZTFjNS00MTU3LTk5MTAtMTJmNzcyMThlYTllIiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9','https://app.powerbi.com/view?r=eyJrIjoiMDVjY2VmMTItMmU2Ny00MmQ1LTg4MzUtN2I2ZWE4MDk1N2VhIiwidCI6ImVhYjdiZThmLTQ5ZDQtNDg5NC04ZmQ0LWM5ZjE0YzM2ZmY5NCJ9'];
let renderedPortfolioLanguage='';const renderPersonalPortfolio=()=>{const language=document.documentElement.lang==='en'?'en':'pt';if(renderedPortfolioLanguage===language)return;const portfolio=personalPortfolio[language];const container=document.querySelector('.portfolio-grid');if(!container)return;document.querySelector('.portfolio .section-lead').textContent=portfolio.lead;container.innerHTML=`<a class="featured-project" href="${personalPortfolioLinks[0]}" target="_blank" rel="noreferrer"><div class="chart-art"><div class="analytics-head"><b>${portfolio.featured}</b><span>POWER BI · PERSONAL DASHBOARD</span></div><div class="analytics-kpis"><div><small>ANÁLISE</small><strong>01</strong></div><div><small>INDICADORES</small><strong>KPIs</strong></div><div><small>FOCO</small><strong>RESULTADOS</strong></div></div><div class="analytics-bars"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div><small>PROJETO 01 · POWER BI</small><h3>${portfolio.featured}</h3><p>${portfolio.description}</p><strong>${language==='en'?'VIEW DASHBOARD':'VER DASHBOARD'} ↗</strong></div></a><div class="project-list">${portfolio.projects.map((project,index)=>`<a href="${personalPortfolioLinks[index+1]}" target="_blank" rel="noreferrer"><span>${String(index+2).padStart(2,'0')}</span><div><small>POWER BI · PERSONAL DASHBOARD</small><h3>${project}</h3></div><b>↗</b></a>`).join('')}</div>`;renderedPortfolioLanguage=language;};renderPersonalPortfolio();setInterval(renderPersonalPortfolio,250);
